apiVersion: plugin.halo.run/v1alpha1
kind: Plugin
metadata:
  name: halo-multi-publisher
spec:
  enabled: true
  requires: ">=2.20.0"
  author:
    name: Corps-Cy
    website: https://github.com/Corps-Cy
  logo: /assets/logo.svg
  homepage: https://github.com/Corps-Cy/halo-multi-publisher#readme
  displayName: 多平台文章同步
  description: 将 Halo 博客文章自动同步到微信公众号、掘金等平台
  license:
    - name: Apache-2.0
    - url: https://www.apache.org/licenses/LICENSE-2.0
  settingName: halo-multi-publisher-settings
  configMapName: halo-multi-publisher-config
